// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyIqIFx9UwtMz0DjPEwL7V6EgNsLHXLuo',
    appId: '1:515794293459:web:c903c022360595ebdbba26',
    messagingSenderId: '515794293459',
    projectId: 'loginapp-76d14',
    authDomain: 'loginapp-76d14.firebaseapp.com',
    storageBucket: 'loginapp-76d14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKMCLaWCsIUEJWphhfpVCNtRDS1oPhtAA',
    appId: '1:515794293459:android:bcf459eda9ddda09dbba26',
    messagingSenderId: '515794293459',
    projectId: 'loginapp-76d14',
    storageBucket: 'loginapp-76d14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnwA9JZxOjeczpsmbKXgt5I0RGUs4gtDg',
    appId: '1:515794293459:ios:7af5c976e3ea0855dbba26',
    messagingSenderId: '515794293459',
    projectId: 'loginapp-76d14',
    storageBucket: 'loginapp-76d14.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnwA9JZxOjeczpsmbKXgt5I0RGUs4gtDg',
    appId: '1:515794293459:ios:7af5c976e3ea0855dbba26',
    messagingSenderId: '515794293459',
    projectId: 'loginapp-76d14',
    storageBucket: 'loginapp-76d14.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
